/**
 * SAP Compass — agent.js
 * ─────────────────────────────────────────────────────────────────
 * Handles all runtime logic:
 *   - Profile load / save / reset
 *   - Tab navigation
 *   - Claude API calls (with optional live web search)
 *   - Chat rendering (messages, typing indicator)
 *   - Curriculum, SWOT, Glossary rendering
 *   - Onboarding flow (3-step profile wizard)
 *
 * Do not edit this file unless you are changing behaviour.
 * To change content, edit config.js instead.
 * ─────────────────────────────────────────────────────────────────
 */

/* ─── State ────────────────────────────────────────────────────── */
let profile = { background: null, curiosity: null, style: null };
let messages = [];         // full conversation history sent to API
let isLoading = false;
let currentStep = 0;
let onboardSelections = {};

const TAB_NAMES = ["chat", "curriculum", "swot", "glossary", "onboard"];

/* ─── Profile helpers ─────────────────────────────────────────── */
function loadProfile() {
  try {
    const stored = sessionStorage.getItem(AGENT_CONFIG.storageKey);
    if (stored) profile = JSON.parse(stored);
  } catch (e) {}
}

function saveProfile() {
  try {
    sessionStorage.setItem(AGENT_CONFIG.storageKey, JSON.stringify(profile));
  } catch (e) {}
}

function getBgObj() {
  return BACKGROUNDS.find(b => b.id === profile.background) || null;
}

/* ─── System prompt ───────────────────────────────────────────── */
function buildSystemPrompt() {
  const bg = getBgObj();
  const bgNote = bg
    ? `The user's professional background is: ${bg.label}.\nUse this analogy framework when explaining SAP concepts: ${bg.analogy}`
    : "Ask about the user's background if it becomes relevant.";

  const curiosityNote = profile.curiosity
    ? `Their stated main curiosity: ${profile.curiosity}.`
    : "";

  const styleNote = profile.style
    ? `Their preferred learning style: ${profile.style}.`
    : "";

  const techArchExtra =
    profile.background === "techarchitect"
      ? `
TECH ARCHITECT GUIDANCE:
- This person thinks in layers, patterns, and system design. Use architecture metaphors freely.
- Map SAP to familiar patterns: Clean Core = separation of concerns, BTP = API gateway + PaaS,
  Joule = AI orchestration layer, Basis = infrastructure/platform team, Landscape = environment tiers,
  Transport = CI/CD pipeline, ABAP = typed compiled language with its own runtime.
- They can handle more technical depth — do not oversimplify.
- Connect answers to enterprise architecture governance and how SAP decisions affect the broader solution landscape.
- When relevant, discuss integration patterns: APIs, events, iFlows, side-by-side extensions on BTP.`
      : "";

  return `You are SAP Compass — a sharp, warm, and knowledgeable SAP expert helping new leaders understand SAP quickly and confidently. You orient leaders in the SAP world, just as a compass orients a traveller in unfamiliar terrain.

${bgNote}
${curiosityNote}
${styleNote}
${techArchExtra}

YOUR RULES:
1. Always explain SAP concepts through analogies that match the user's professional background.
2. End EVERY answer with a "So what for you as a leader?" section — 1-2 sentences connecting the concept to a real leadership decision they will face.
3. Keep answers concise — 150 words maximum unless the user explicitly asks for more depth.
4. Never use jargon without explaining it in plain terms first.
5. You have live web search capability. When asked about 2026 trends, recent SAP news, security incidents, or anything current, tell the user you are pulling the latest information before answering.
6. Be warm and encouraging — this is a new leader learning a new domain. Make them feel capable, not overwhelmed.
7. You are called SAP Compass. Reference this identity naturally in your first message but not repeatedly.
8. If you do not know something, say so — never fabricate SAP facts or figures.`;
}

/* ─── Claude API call ─────────────────────────────────────────── */
async function callClaude(userMsg) {
  messages.push({ role: "user", content: userMsg });

  const body = {
    model: AGENT_CONFIG.model,
    max_tokens: AGENT_CONFIG.maxTokens,
    system: buildSystemPrompt(),
    messages
  };

  if (AGENT_CONFIG.webSearch) {
    body.tools = [{ type: "web_search_20250305", name: "web_search" }];
  }

  const resp = await fetch(AGENT_CONFIG.apiEndpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });

  const data = await resp.json();

  // Extract all text blocks (web search may produce multiple content blocks)
  const text = (data.content || [])
    .filter(b => b.type === "text")
    .map(b => b.text)
    .join("");

  // Store full assistant content (including tool_use blocks) for context continuity
  messages.push({ role: "assistant", content: data.content || [] });

  return text || "I could not get a response. Please try again.";
}

/* ─── Chat rendering ──────────────────────────────────────────── */
function renderMsgText(text) {
  return text
    .replace(/\*\*(.*?)\*\*/g, "<b>$1</b>")
    .replace(/\n/g, "<br>");
}

function addMsg(role, text) {
  const container = document.getElementById("chat-msgs");
  const div = document.createElement("div");
  div.className = "msg " + role;
  const avatar =
    role === "agent"
      ? '<i class="ti ti-compass" style="font-size:14px"></i>'
      : "You";
  div.innerHTML = `
    <div class="msg-avatar">${avatar}</div>
    <div class="msg-bubble">${renderMsgText(text)}</div>
  `;
  container.appendChild(div);
  container.scrollTop = container.scrollHeight;
}

function showTyping() {
  const container = document.getElementById("chat-msgs");
  const div = document.createElement("div");
  div.className = "msg agent";
  div.id = "typing-indicator";
  div.innerHTML = `
    <div class="msg-avatar"><i class="ti ti-compass" style="font-size:14px"></i></div>
    <div class="typing"><span></span><span></span><span></span></div>
  `;
  container.appendChild(div);
  container.scrollTop = container.scrollHeight;
}

function removeTyping() {
  const t = document.getElementById("typing-indicator");
  if (t) t.remove();
}

/* ─── Send message ────────────────────────────────────────────── */
async function sendMsg() {
  const input = document.getElementById("chat-input");
  const msg = input.value.trim();
  if (!msg || isLoading) return;

  isLoading = true;
  input.value = "";
  input.style.height = "";
  document.getElementById("send-btn").disabled = true;

  addMsg("user", msg);
  showTyping();

  try {
    const reply = await callClaude(msg);
    removeTyping();
    addMsg("agent", reply);
  } catch (e) {
    removeTyping();
    addMsg("agent", "Something went wrong connecting to the AI. Please check your connection and try again.");
    console.error("SAP Compass API error:", e);
  }

  isLoading = false;
  document.getElementById("send-btn").disabled = false;
  input.focus();
}

function quickAsk(q) {
  document.getElementById("chat-input").value = q;
  sendMsg();
}

function handleKey(e) {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    sendMsg();
  }
}

function autoResize(el) {
  el.style.height = "auto";
  el.style.height = Math.min(el.scrollHeight, 90) + "px";
}

/* ─── Quick buttons ───────────────────────────────────────────── */
function setQuickBtns() {
  const bg = getBgObj();
  const specific = bg && QUICK_QUESTIONS[bg.id] ? QUICK_QUESTIONS[bg.id] : [];
  const btns = [...specific, ...QUICK_QUESTIONS.base].slice(0, 5);
  document.getElementById("quick-btns").innerHTML = btns
    .map(b => `<button class="qbtn" onclick="quickAsk(this.dataset.q)" data-q="${b.replace(/"/g, "&quot;")}">${b}</button>`)
    .join("");
}

/* ─── Tab navigation ──────────────────────────────────────────── */
function showTab(name) {
  document.querySelectorAll(".tab").forEach((t, i) =>
    t.classList.toggle("active", TAB_NAMES[i] === name)
  );
  document.querySelectorAll(".pane").forEach(p => p.classList.remove("active"));
  document.getElementById("pane-" + name).classList.add("active");

  if (name === "curriculum") renderCurriculum();
  if (name === "swot") renderSwot();
  if (name === "glossary") renderGlossary("");
  if (name === "onboard") renderOnboard();
}

/* ─── Curriculum rendering ────────────────────────────────────── */
function renderCurriculum() {
  document.getElementById("curriculum-pane").innerHTML = CURRICULUM.map(
    p => `
    <div class="phase-card">
      <div class="phase-header" onclick="togglePhase(${p.phase})">
        <div class="phase-num">${p.phase}</div>
        <div class="phase-title">${p.title}</div>
        <span class="phase-badge ${p.badge}">${p.label}</span>
        <i class="ti ti-chevron-down phase-chevron" id="chevron-${p.phase}"></i>
      </div>
      <div class="phase-body" id="phase-body-${p.phase}">
        ${p.topics
          .map(
            t => `
          <div class="phase-topic">
            <i class="ti ti-circle-dot"></i>
            <span>${t}</span>
            <button class="ask-btn" onclick="askAbout('${t.replace(/'/g, "&#39;")}')">Ask ↗</button>
          </div>`
          )
          .join("")}
      </div>
    </div>`
  ).join("");
}

function togglePhase(n) {
  const body = document.getElementById("phase-body-" + n);
  const chev = document.getElementById("chevron-" + n);
  const isOpen = body.classList.contains("open");
  document.querySelectorAll(".phase-body").forEach(b => b.classList.remove("open"));
  document.querySelectorAll(".phase-chevron").forEach(c => (c.style.transform = ""));
  if (!isOpen) {
    body.classList.add("open");
    chev.style.transform = "rotate(180deg)";
  }
}

function askAbout(topic) {
  showTab("chat");
  document.getElementById("chat-input").value = `Explain "${topic}" for me as a new leader`;
  sendMsg();
}

/* ─── SWOT rendering ──────────────────────────────────────────── */
function renderSwot() {
  const sections = [
    { key: "strengths",    label: "STRENGTHS",    cls: "swot-s", dot: "dot-s" },
    { key: "weaknesses",   label: "WEAKNESSES",   cls: "swot-w", dot: "dot-w" },
    { key: "opportunities",label: "OPPORTUNITIES",cls: "swot-o", dot: "dot-o" },
    { key: "threats",      label: "THREATS",      cls: "swot-t", dot: "dot-t" }
  ];
  document.getElementById("swot-pane").innerHTML = sections
    .map(
      s => `
    <div class="swot-card">
      <div class="swot-label ${s.cls}">${s.label}</div>
      ${SWOT[s.key]
        .map(
          item => `
        <div class="swot-item">
          <div class="swot-dot ${s.dot}"></div>
          <span>${item}</span>
        </div>`
        )
        .join("")}
    </div>`
    )
    .join("");
}

/* ─── Glossary rendering ──────────────────────────────────────── */
function renderGlossary(filter) {
  const lower = filter.toLowerCase();
  const terms = GLOSSARY.filter(
    g =>
      !filter ||
      g.term.toLowerCase().includes(lower) ||
      g.def.toLowerCase().includes(lower)
  );
  document.getElementById("glossary-list").innerHTML = terms.length
    ? terms
        .map(
          g => `
      <div class="gterm">
        <div class="gterm-word">${g.term}</div>
        <div class="gterm-def">${g.def}</div>
        <div class="gterm-analogy"><i class="ti ti-bulb" style="font-size:11px"></i> ${g.analogy}</div>
      </div>`
        )
        .join("")
    : `<div class="glossary-empty">No terms match your search.</div>`;
}

function filterGlossary(val) {
  renderGlossary(val);
}

/* ─── Profile pill ────────────────────────────────────────────── */
function updateProfilePill() {
  const pill = document.getElementById("profile-pill");
  const bg = getBgObj();
  if (bg) {
    pill.textContent =
      bg.id === "techarchitect" ? "Tech Architect" : bg.label.split("/")[0].trim();
    pill.style.display = "inline";
  } else {
    pill.style.display = "none";
  }
}

/* ─── Onboarding ──────────────────────────────────────────────── */
const ONBOARD_STEPS = [
  {
    q: "What's your professional background?",
    key: "background",
    opts: BACKGROUNDS.map(b => ({
      value: b.id,
      label: b.label,
      icon: b.icon,
      isNew: !!b.isNew
    }))
  },
  {
    q: "What's your biggest curiosity about SAP right now?",
    key: "curiosity",
    opts: [
      { value: "what it does",      label: "What SAP actually does day-to-day",        icon: "ti-search" },
      { value: "how my team uses it",label: "How my Basis team uses SAP",              icon: "ti-users" },
      { value: "where it is headed", label: "Where SAP is headed — AI, cloud, 2027",   icon: "ti-rocket" },
      { value: "risks i should know",label: "Risks and issues I should know now",      icon: "ti-shield-exclamation" }
    ]
  },
  {
    q: "How do you prefer to learn?",
    key: "style",
    opts: [
      { value: "analogies",     label: "Give me analogies from my world",   icon: "ti-arrows-transfer-down" },
      { value: "big picture",   label: "Show me the big picture first",     icon: "ti-world" },
      { value: "essentials only",label: "Just the leadership essentials",   icon: "ti-list-check" },
      { value: "deep dive",     label: "I want the full detail",            icon: "ti-zoom-in" }
    ]
  }
];

function renderOnboard() {
  const wrap = document.getElementById("onboard-wrap");
  const hasProfile = profile.background && profile.curiosity && profile.style;

  if (hasProfile) {
    const bg = getBgObj();
    wrap.innerHTML = `
      <div class="welcome-box">
        <div class="welcome-title">Your learning profile is set</div>
        <div class="welcome-sub">SAP Compass adapts all explanations to your ${bg ? bg.label : ""} background. Every answer ends with a leadership "so what?" tailored for you.</div>
      </div>
      <div class="profile-summary">
        <div class="onboard-opt selected">
          <i class="ti ti-user-circle"></i>
          <div><div class="opt-label">Background</div><div class="opt-value">${bg ? bg.label : ""}</div></div>
        </div>
        <div class="onboard-opt selected">
          <i class="ti ti-search"></i>
          <div><div class="opt-label">Main curiosity</div><div class="opt-value">${profile.curiosity}</div></div>
        </div>
        <div class="onboard-opt selected">
          <i class="ti ti-book"></i>
          <div><div class="opt-label">Learning style</div><div class="opt-value">${profile.style}</div></div>
        </div>
      </div>
      <button class="reset-btn" onclick="resetProfile()">
        <i class="ti ti-refresh"></i> Reset profile
      </button>
    `;
    return;
  }

  currentStep = 0;
  onboardSelections = {};
  renderOnboardStep(wrap);
}

function renderOnboardStep(wrap) {
  const step = ONBOARD_STEPS[currentStep];
  const isLast = currentStep === ONBOARD_STEPS.length - 1;
  wrap.innerHTML = `
    <div class="onboard-progress-row">
      <div class="onboard-step-label">Step ${currentStep + 1} of ${ONBOARD_STEPS.length}</div>
      <div class="onboard-progress-dots">
        ${ONBOARD_STEPS.map((_, i) =>
          `<div class="progress-dot ${i <= currentStep ? "active" : ""}"></div>`
        ).join("")}
      </div>
    </div>
    <div class="onboard-q">${step.q}</div>
    <div class="onboard-opts">
      ${step.opts
        .map(
          o => `
        <div class="onboard-opt" onclick="selectOpt('${step.key}','${o.value}',this)">
          <i class="ti ${o.icon}"></i>
          <span>${o.label}${o.isNew ? '<span class="new-tag">new</span>' : ""}</span>
        </div>`
        )
        .join("")}
    </div>
    <button class="start-btn" id="next-btn" disabled onclick="nextStep()">
      ${isLast ? "Start your journey" : "Next →"}
    </button>
  `;
}

function selectOpt(key, value, el) {
  document.querySelectorAll("#onboard-wrap .onboard-opt").forEach(o =>
    o.classList.remove("selected")
  );
  el.classList.add("selected");
  onboardSelections[key] = value;
  document.getElementById("next-btn").disabled = false;
}

function nextStep() {
  const step = ONBOARD_STEPS[currentStep];
  if (!onboardSelections[step.key]) return;
  profile[step.key] = onboardSelections[step.key];
  currentStep++;

  if (currentStep >= ONBOARD_STEPS.length) {
    saveProfile();
    updateProfilePill();
    renderOnboard();
    initChat();
    showTab("chat");
  } else {
    onboardSelections = {};
    renderOnboardStep(document.getElementById("onboard-wrap"));
  }
}

function resetProfile() {
  profile = { background: null, curiosity: null, style: null };
  messages = [];
  saveProfile();
  updateProfilePill();
  currentStep = 0;
  onboardSelections = {};
  renderOnboard();
}

/* ─── Chat initialisation ─────────────────────────────────────── */
function initChat() {
  document.getElementById("chat-msgs").innerHTML = "";
  messages = [];
  const bg = getBgObj();

  const greetings = {
    techarchitect: `Welcome! I'm **SAP Compass**, and I can tell this will be a great conversation.\n\nAs a **Tech Architect**, SAP maps naturally to patterns you already know:\n- **Basis** = infrastructure & platform team\n- **BTP** = middleware, API gateway & PaaS layer\n- **S/4HANA** = core application tier (in-memory, HANA)\n- **Joule AI** = intelligence & orchestration layer\n- **Clean Core** = separation of concerns, applied to ERP\n\nWhat would you like to architect first?`,
    default: `Welcome! I'm **SAP Compass** — your guide through the SAP world, tailored for your **${bg ? bg.label : ""}** background.\n\nI explain SAP through analogies from your world, pull live 2026 data when you ask about trends, and end every answer with a leadership "so what?" — so you always know why it matters.\n\nWhat would you like to explore first?`
  };

  const greeting =
    bg && greetings[bg.id] ? greetings[bg.id] : greetings.default;
  addMsg("agent", greeting);
  setQuickBtns();
}

function initDefault() {
  document.getElementById("chat-msgs").innerHTML = "";
  addMsg(
    "agent",
    `Welcome to **SAP Compass** — your guide to the SAP world.\n\nI help new leaders get oriented in SAP quickly, confidently, and from a leadership lens.\n\nHead to the **Profile** tab to personalise your experience, or ask me anything below.`
  );
  setQuickBtns();
}

/* ─── Bootstrap ───────────────────────────────────────────────── */
(function init() {
  loadProfile();
  updateProfilePill();
  renderCurriculum();
  renderSwot();
  renderGlossary("");

  if (profile.background && profile.curiosity && profile.style) {
    initChat();
  } else {
    initDefault();
    showTab("onboard");
    renderOnboard();
  }
})();
